In [1]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()#set_style("dark")

In [3]:
a = []
a.append([2.5, 1.6, 5.9])
a.append([7.2, 4.3, 2.1])
a.append([3.4, 5.8, 1.6])
a.append([5.6, 3.6, 6.8])
a.append([4.8, 7.2, 3.1])
a.append([8.1, 4.9, 8.3])
a.append([6.3, 4.8, 2.4])
a = np.array(a)

In [4]:
targs = [0,1,1,0,1,0,1]

In [5]:
a

array([[2.5, 1.6, 5.9],
       [7.2, 4.3, 2.1],
       [3.4, 5.8, 1.6],
       [5.6, 3.6, 6.8],
       [4.8, 7.2, 3.1],
       [8.1, 4.9, 8.3],
       [6.3, 4.8, 2.4]])

In [6]:
a[:,2]

array([5.9, 2.1, 1.6, 6.8, 3.1, 8.3, 2.4])

In [7]:
a[:,1][0]

1.6

In [8]:
A0 = []
B0 = []

A1 = []
B1 = []

A2 = []
B2 = []

for i, targ in enumerate(targs):
    if targ == 0:
        A0.append(a[:,0][i])
        A1.append(a[:,1][i])
        A2.append(a[:,2][i])
    else:
        B0.append(a[:,0][i])
        B1.append(a[:,1][i])
        B2.append(a[:,2][i])

In [9]:
varA0, varB0 = np.var(A0), np.var(B0)
varA1, varB1 = np.var(A1), np.var(B1)
varA2, varB2 = np.var(A2), np.var(B2)

r0 = (varA0/len(A0)) + (varB0/len(B0))
r1 = (varA1/len(A1)) + (varB1/len(B1))
r2 = (varA2/len(A2)) + (varB2/len(B2))

SE0 = math.sqrt(r0)
SE1 = math.sqrt(r1)
SE2 = math.sqrt(r2)

s0 =  abs(np.array(A0).mean() - np.array(B0).mean())
s1 =  abs(np.array(A1).mean() - np.array(B1).mean())
s2 =  abs(np.array(A2).mean() - np.array(B2).mean())

rank0 = s0/SE0
rank1 = s1/SE1
rank2 = s2/SE2

sorted([rank0, rank1, rank2], reverse=True)

[7.427485026503828, 2.249249097997478, 0.016577179105925148]

## Relief

In [38]:
b = []
b.append([2.7, 3.4, 1])
b.append([3.1, 6.2, 2])
b.append([4.5, 2.8, 1])
b.append([5.3, 5.8, 2])
b.append([6.6, 3.1, 1])
b.append([5.0, 4.1, 2])
# b = np.array(b)

In [39]:
b = []
b.append([2.7, 3.4, 1, 'A'])
b.append([3.1, 6.2, 2, 'A'])
b.append([4.5, 2.8, 1, 'B'])
b.append([5.3, 5.8, 2, 'B'])
b.append([6.6, 3.1, 1, 'A'])
b.append([5.0, 4.1, 2, 'B'])

In [20]:
targets = ['A','A','B','B','A','B']

In [19]:
b

array([[2.7, 3.4, 1. ],
       [3.1, 6.2, 2. ],
       [4.5, 2.8, 1. ],
       [5.3, 5.8, 2. ],
       [6.6, 3.1, 1. ],
       [5. , 4.1, 2. ]])

In [16]:
list(range(0,3))

[0, 1, 2]

In [40]:
def distance(a, b):
    x1, y1, z1 = a[0], a[1], a[2]
    x2, y2, z2 = b[0], b[1], b[2]
    d = math.sqrt(math.pow((x2 - x1), 2) + math.pow((y2 - y1),2) + math.pow((z2 - z1), 2))/2
    return d

In [41]:
def qualityScore(X, H, M, m):
    quality = (-math.pow((X-H), 2) + math.pow((X-M), 2))/m
    return quality

In [42]:
def relief(b):
    Wajs = []
    for m, sample in enumerate(b):
        Waj = 0.0
        nearestH = []
        nearestM = []

        hits = []
        misses = []

        distsH = []
        distsM = []

        Xclass = targets[m]
        samplesMinusX = b.copy()
        samplesMinusX.remove(sample)

        for sample2 in samplesMinusX:
            if sample[len(sample)-1] == sample2[len(sample2)-1]:
                hits.append(sample2)
                distsH.append(distance(sample, sample2))
            else:
                misses.append(sample2)
                distsM.append(distance(sample, sample2))


        nearestH = hits[min(range(len(distsH)), key=distsH.__getitem__)]
        nearestM = misses[min(range(len(distsM)), key=distsM.__getitem__)]


        ## feature wise quality update 
        for i in range(0,3):
            Waj += qualityScore(sample[i], nearestH[i], nearestM[i], m+1)

        Wajs.append(Waj)
        print(m)
    return Wajs

In [43]:
relief(b)

0
1
2
3
4
5


[-5.400000000000002,
 -2.0000000000000013,
 0.22000000000000003,
 0.5049999999999997,
 -2.1599999999999993,
 0.26999999999999974]

In [35]:
        
samplesMinusX = b.copy()
samplesMinusX.remove(b[0])

In [36]:
samplesMinusX

[[3.1, 6.2, 2], [4.5, 2.8, 1], [5.3, 5.8, 2], [6.6, 3.1, 1], [5.0, 4.1, 2]]

In [45]:
b[0][len(b[0])-1]

'A'